name: Simple CI Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Copy .env file
      run: |
        echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> portfolio/.env
        echo "DEBUG=${{ secrets.DEBUG }}" >> portfolio/.env
        echo "DJANGO_ALLOWED_HOSTS=${{ secrets.DJANGO_ALLOWED_HOSTS }}" >> portfolio/.env
        echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> portfolio/.env
        echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> portfolio/.env
        echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> portfolio/.env
        echo "DATABASE_URL=postgres://${{ secrets.POSTGRES_USER }}:${{ secrets.POSTGRES_PASSWORD }}@db:5432/${{ secrets.POSTGRES_DB }}" >> portfolio/.env
    - name: Display .env content
      run: cat portfolio/.env
