name: Django CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r SRE_JR/portfolio/requirements.txt
        
    - name: Copy .env file
      run: |
        echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> SRE_JR/portfolio/.env
        echo "DEBUG=${{ secrets.DEBUG }}" >> SRE_JR/portfolio/.env
        echo "DJANGO_ALLOWED_HOSTS=${{ secrets.DJANGO_ALLOWED_HOSTS }}" >> SRE_JR/portfolio/.env
        echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> SRE_JR/portfolio/.env
        echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> SRE_JR/portfolio/.env
        echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> SRE_JR/portfolio/.env
        echo "DATABASE_URL=postgres://${{ secrets.POSTGRES_USER }}:${{ secrets.POSTGRES_PASSWORD }}@db:5432/${{ secrets.POSTGRES_DB }}" >> SRE_JR/portfolio/.env

    - name: Wait for PostgreSQL to be ready
      run: |
        until pg_isready -h db -p 5432 -U ${{ secrets.POSTGRES_USER }}; do
          echo "Waiting for PostgreSQL..."
          sleep 2
        done

    - name: Run migrations
      run: python SRE_JR/portfolio/manage.py migrate

    - name: Run tests
      run: python SRE_JR/portfolio/manage.py test

    - name: Deploy to DigitalOcean
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}
      run: |
        chmod 600 id_ed25519
        ssh-keyscan -H ${{ secrets.DJANGO_ALLOWED_HOSTS }} >> known_hosts
        scp -i id_ed25519 -o StrictHostKeyChecking=no -o UserKnownHostsFile=known_hosts -r SRE_JR/portfolio root@${{ secrets.DJANGO_ALLOWED_HOSTS }}:/root/SRE_JR/portfolio
        scp -i id_ed25519 -o StrictHostKeyChecking=no -o UserKnownHostsFile=known_hosts SRE_JR/portfolio/.env root@${{ secrets.DJANGO_ALLOWED_HOSTS }}:/root/SRE_JR/portfolio/.env
        ssh -i id_ed25519 -o StrictHostKeyChecking=no -o UserKnownHostsFile=known_hosts root@${{ secrets.DJANGO_ALLOWED_HOSTS }} 'cd /root/SRE_JR/portfolio && docker-compose build && docker-compose up -d'
