name: Django CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Compose
      run: sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose

    - name: Make Docker Compose executable
      run: sudo chmod +x /usr/local/bin/docker-compose

    - name: Build and run containers
      run: |
        docker-compose up -d --build

    - name: Wait for PostgreSQL to be ready
      run: |
        echo "Waiting for PostgreSQL to be ready..."
        docker-compose exec db bash -c "until pg_isready -h localhost -p 5432 -U ${POSTGRES_USER}; do sleep 1; done"

    - name: Run migrations
      run: docker-compose exec web python manage.py migrate

    - name: Run tests
      run: docker-compose exec web python manage.py test

    - name: Deploy to DigitalOcean
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}
      run: |
        chmod 600 id_ed25519
        ssh-keyscan -H ${{ secrets.DJANGO_ALLOWED_HOSTS }} >> known_hosts
        scp -i id_ed25519 -o StrictHostKeyChecking=no -o UserKnownHostsFile=known_hosts -r portfolio root@${{ secrets.DJANGO_ALLOWED_HOSTS }}:/root/SRE_JR/portfolio
        scp -i id_ed25519 -o StrictHostKeyChecking=no -o UserKnownHostsFile=known_hosts portfolio/.env root@${{ secrets.DJANGO_ALLOWED_HOSTS }}:/root/SRE_JR/portfolio/.env
        ssh -i id_ed25519 -o StrictHostKeyChecking=no -o UserKnownHostsFile=known_hosts root@${{ secrets.DJANGO_ALLOWED_HOSTS }} 'cd /root/SRE_JR/portfolio && docker-compose build && docker-compose up -d'
