name: Django CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose

    - name: Create .env file
      run: |
        echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> portfolio/.env
        echo "DEBUG=1" >> portfolio/.env
        echo "DJANGO_ALLOWED_HOSTS=${{ secrets.DJANGO_ALLOWED_HOSTS }}" >> portfolio/.env
        echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> portfolio/.env
        echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> portfolio/.env
        echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> portfolio/.env
        echo "DATABASE_URL=postgres://${{ secrets.POSTGRES_USER }}:${{ secrets.POSTGRES_PASSWORD }}@db:5432/${{ secrets.POSTGRES_DB }}" >> portfolio/.env

    - name: Clean up
      working-directory: ./portfolio
      run: |
        docker-compose down -v

    - name: Build and run containers
      working-directory: ./portfolio
      run: |
        docker-compose up -d --build
        sleep 10

    - name: Check Docker version
      run: docker --version

    - name: Check Docker Compose version
      run: docker-compose --version

    - name: Wait for PostgreSQL to be ready
      working-directory: ./portfolio
      run: |
        echo "Waiting for PostgreSQL to be ready..."
        until docker-compose exec -T db pg_isready -U ${{ secrets.POSTGRES_USER }}; do
          echo "PostgreSQL is not ready yet. Waiting..."
          sleep 5
        done

    - name: Run migrations
      working-directory: ./portfolio
      run: docker-compose exec -T web python manage.py migrate

    - name: Run tests
      working-directory: ./portfolio
      run: docker-compose exec -T web python manage.py test

    - name: Setup SSH
      run: |
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > id_ed25519
        chmod 600 id_ed25519

    - name: Copy Docker Compose logs
      working-directory: ./portfolio
      run: |
        mkdir -p logs
        docker-compose logs > logs/docker-compose.log
        cat logs/docker-compose.log

    - name: Deploy to DigitalOcean
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}
      run: |
        ssh-keyscan -H ${{ secrets.DJANGO_ALLOWED_HOSTS }} >> known_hosts
        scp -i id_ed25519 -o StrictHostKeyChecking=no -o UserKnownHostsFile=known_hosts -r portfolio root@${{ secrets.DJANGO_ALLOWED_HOSTS }}:/root/SRE_JR/portfolio
        scp -i id_ed25519 -o StrictHostKeyChecking=no -o UserKnownHostsFile=known_hosts portfolio/.env root@${{ secrets.DJANGO_ALLOWED_HOSTS }}:/root/SRE_JR/portfolio/.env
        ssh -i id_ed25519 -o StrictHostKeyChecking=no -o UserKnownHostsFile=known_hosts root@${{ secrets.DJANGO_ALLOWED_HOSTS }} 'cd /root/SRE_JR/portfolio && docker-compose build && docker-compose up -d'
