name: CI/CD

on:
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r portfolio/requirements.txt

    - name: Set environment variables
      run: |
        echo "DJANGO_ALLOWED_HOSTS=${{ secrets.DJANGO_ALLOWED_HOSTS }}" >> $GITHUB_ENV
        echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> $GITHUB_ENV
        echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> $GITHUB_ENV

    - name: Run tests
      run: |
        cd portfolio
        python manage.py test

    - name: Setup SSH
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts

    - name: Verify SSH connection
      run: |
        ssh -i ~/.ssh/id_ed25519 -o UserKnownHostsFile=~/.ssh/known_hosts -o StrictHostKeyChecking=no root@64.226.81.5 'echo "Connection successful"'

    - name: Deploy to DigitalOcean
      run: |
        scp -i ~/.ssh/id_ed25519 -o UserKnownHostsFile=~/.ssh/known_hosts -r portfolio root@64.226.81.5:/SRE_JR/
        ssh -i ~/.ssh/id_ed25519 -o UserKnownHostsFile=~/.ssh/known_hosts root@64.226.81.5 'cd /SRE_JR/portfolio/ && docker-compose down && docker-compose up -d'
